#!/usr/bin/env node
/* Research-only cross-market OOS test.
   This is intentionally derived from the exact historical X fixed-target replay
   (commit 11b94eb7e73c81a6759a4c4e23665d451b6c2280), changing only the target market
   and evaluation window. Core T32/VWAP entry, -4%/12h gate, limit/TTL, fees,
   stop, TP, 90m hold, slippage and max-2/day semantics are preserved. */
const fs=require('fs'),path=require('path');
const API='https://data-api.binance.vision/api/v3/klines',M=60000;
const START=Date.parse('2026-02-01T00:00:00Z'),END=Date.parse('2026-03-01T00:00:00Z');
const FEE=.0021,SLIP=.0008,TARGET=2.5,STOP=-1.2,PEAKN=720,CAP=2;
const sum=x=>x.reduce((a,b)=>a+b,0),avg=x=>x.length?sum(x)/x.length:0,pct=(a,b)=>(b/a-1)*100;
const net=(e,x)=>((x*(1-FEE))/(e*(1+FEE))-1)*100,p4n=(e,n)=>e*(1+n/100)*(1+FEE)/(1-FEE);
async function fetchS(s,st,en){const o=[];for(let c=st;c<en;){const r=await fetch(`${API}?symbol=${s}&interval=1m&startTime=${c}&endTime=${en-1}&limit=1000`);if(!r.ok)throw Error(`${s} ${r.status}`);const p=await r.json();if(!p.length)break;o.push(...p);c=+p[p.length-1][0]+M}return o.map(x=>({t:+x[0],o:+x[1],h:+x[2],l:+x[3],c:+x[4],q:+x[7],bq:+x[10]}))}
function pre(a){const n=a.length,vw=new Float64Array(n),dv=new Float64Array(n),bu=new Float64Array(n);let q=0,pq=0;const qq=[],pp=[];for(let i=0;i<n;i++){const x=a[i],z=((x.h+x.l+x.c)/3)*x.q;qq.push(x.q);pp.push(z);q+=x.q;pq+=z;if(qq.length>60){q-=qq.shift();pq-=pp.shift()}vw[i]=q?pq/q:x.c;dv[i]=pct(vw[i],x.c);bu[i]=x.q?x.bq/x.q:.5}return{vw,dv,bu}}
function highs(a,n){const o=new Float64Array(a.length),dq=[];for(let i=0;i<a.length;i++){while(dq.length&&dq[0]<i-n+1)dq.shift();while(dq.length&&a[dq[dq.length-1]].h<=a[i].h)dq.pop();dq.push(i);o[i]=a[dq[0]].h}return o}
function ok(a,p,i){return p.dv[i]<=-.40&&a[i].c>a[i].o&&p.bu[i]>=.50&&p.bu[i]>p.bu[i-1]}
function fill(a,i){const px=a[i].c*.999;for(let j=i+1;j<=i+2&&j<a.length;j++)if(a[j].l<=px)return{at:j,price:Math.min(px,a[j].o)};return null}
function closeFixed(a,e){const tp=p4n(e.price,TARGET),sl=p4n(e.price,STOP),end=Math.min(a.length-1,e.at+90);for(let j=e.at+1;j<=end;j++){const x=a[j];if(x.l<=sl)return{at:j,pnl:net(e.price,Math.min(sl,x.o)*(1-SLIP)),why:'STOP',exit:Math.min(sl,x.o)*(1-SLIP)};if(x.h>=tp)return{at:j,pnl:net(e.price,tp),why:'TP',exit:tp}}return{at:end,pnl:net(e.price,a[end].c*(1-SLIP)),why:'TIME',exit:a[end].c*(1-SLIP)}}
function metrics(tr,days){const w=tr.filter(x=>x.pnl>0),l=tr.filter(x=>x.pnl<=0),gp=sum(w.map(x=>x.pnl)),gl=-sum(l.map(x=>x.pnl));let k=1,eq=1,peak=1,mdd=0;for(const x of tr){k*=1+x.pnl/100;eq*=1+x.pnl/100;peak=Math.max(peak,eq);mdd=Math.min(mdd,(eq/peak-1)*100)}return{filled:tr.length,wins:w.length,winRate:tr.length?w.length/tr.length:null,averageNet:tr.length?avg(tr.map(x=>x.pnl)):null,profitFactor:gl?gp/gl:null,compoundPct:(k-1)*100,maxDrawdownPct:mdd,tp:tr.filter(x=>x.why==='TP').length,stop:tr.filter(x=>x.why==='STOP').length,time:tr.filter(x=>x.why==='TIME').length,tradesPerDay:tr.length/days}}
function sim(a,p,pk){let busy=-1,day='',count=0,signals=0,expired=0;const tr=[];for(let i=1500;i<a.length-365;i++){if(i<=busy)continue;const d=new Date(a[i].t).toISOString().slice(0,10);if(d!==day){day=d;count=0}if(count>=CAP)continue;if(a[i].c/pk[i]-1>-.04||!ok(a,p,i))continue;signals++;const e=fill(a,i);if(!e){expired++;busy=i+2;continue}const z=closeFixed(a,e);tr.push({signalAt:new Date(a[i].t).toISOString(),fillAt:new Date(a[e.at].t).toISOString(),entry:e.price,exitAt:new Date(a[z.at].t).toISOString(),exit:z.exit,pnl:z.pnl,why:z.why});busy=z.at;count++}return{signals,expired,...metrics(tr,28),trades:tr}}
(async()=>{const a=await fetchS('SOLUSDT',START,END);if(a.length!==40320)throw Error(`minutes ${a.length}`);const p=pre(a),pk=highs(a,PEAKN),r=sim(a,p,pk);const out={test:'Exact historical X semantics transferred to SOLUSDT',sourceReplayCommit:'11b94eb7e73c81a6759a4c4e23665d451b6c2280',period:['2026-02-01T00:00:00Z','2026-03-01T00:00:00Z'],symbol:'SOLUSDT',parameters:{feeEachSidePct:.21,slippageAdversePct:.08,t32DeviationPct:-.40,buyShareMinPct:50,rollingPeakHours:12,belowPeakPct:4,limitDiscountPct:.10,ttlMinutes:2,targetNetPct:2.5,stopNetPct:-1.2,maxHoldMinutes:90,maxFillsPerUtcDay:2},...r};fs.mkdirSync('sol_x_exact_results',{recursive:true});fs.writeFileSync('sol_x_exact_results/result.json',JSON.stringify(out,null,2));const report=`SOL X EXACT OOS — FEB 2026\n========================\nminutes=${a.length}\nsignals=${r.signals}\nexpired=${r.expired}\nfills=${r.filled}\ntrades/day=${r.tradesPerDay.toFixed(4)}\nwins=${r.wins}\nWR=${(r.winRate*100).toFixed(2)}%\nAvg NET=${r.averageNet.toFixed(6)}%\nPF=${r.profitFactor?.toFixed(6)}\ncompound=${r.compoundPct.toFixed(4)}%\nmaxDD=${r.maxDrawdownPct.toFixed(4)}%\nTP/STOP/TIME=${r.tp}/${r.stop}/${r.time}\n`;fs.writeFileSync('sol_x_exact_results/report.txt',report);console.log(report)})().catch(e=>{console.error(e.stack||e);process.exit(1)});
