#!/usr/bin/env node

/* Fixed cost-aware VWAP and EU session gap-fill replay. Research-only. */
const API="https://data-api.binance.vision/api/v3/klines",M=60000;
const DAYS=Number(process.argv[2]||120),END=Date.parse(process.argv[3]||"2026-04-30T07:55:00Z");
const FEE=.0021,SLIP=.0008,COST_NET=((1-FEE)/(1+FEE)-1)*-100;
const sum=x=>x.reduce((a,b)=>a+b,0),avg=x=>x.length?sum(x)/x.length:0,pct=(a,b)=>(b/a-1)*100;
const net=(e,x)=>((x*(1-FEE))/(e*(1+FEE))-1)*100;
const priceForNet=(e,n)=>e*(1+n/100)*(1+FEE)/(1-FEE);
async function fetchSymbol(symbol,start,end){const out=[];for(let c=start;c<end;){const r=await fetch(`${API}?symbol=${symbol}&interval=1m&startTime=${c}&endTime=${end-1}&limit=1000`);if(!r.ok)throw Error(`${symbol} HTTP ${r.status}`);const p=await r.json();if(!p.length)break;out.push(...p);c=+p[p.length-1][0]+M}return out.map(x=>({t:+x[0],o:+x[1],h:+x[2],l:+x[3],c:+x[4],q:+x[7],bq:+x[10]}))}
function vwap(rows){const q=sum(rows.map(x=>x.q));return q?sum(rows.map(x=>((x.h+x.l+x.c)/3)*x.q))/q:rows.at(-1).c}
function tr(a,i){const x=a[i],p=a[i-1].c;return Math.max(x.h-x.l,Math.abs(x.h-p),Math.abs(x.l-p))/p*100}
function atr(a,i,n){let s=0;for(let j=i-n+1;j<=i;j++)s+=tr(a,j);return s/n}
function buyShare(x){return x.q?x.bq/x.q:.5}
function exitMetrics(trades,signals){const w=trades.filter(x=>x.pnl>0),l=trades.filter(x=>x.pnl<=0),gp=sum(w.map(x=>x.pnl)),gl=-sum(l.map(x=>x.pnl));let eq=0,peak=0,dd=0;for(const x of trades){eq+=x.pnl;peak=Math.max(peak,eq);dd=Math.max(dd,peak-eq)}return{signals,filled:trades.length,wins:w.length,losses:l.length,winRate:trades.length?w.length/trades.length:null,averageNet:trades.length?sum(trades.map(x=>x.pnl))/trades.length:null,totalNetPoints:sum(trades.map(x=>x.pnl)),profitFactor:gl?gp/gl:null,maxSequentialDrawdownPoints:dd,targets:trades.filter(x=>x.why==="TARGET").length,stops:trades.filter(x=>x.why==="STOP").length,breakEven:trades.filter(x=>x.why==="BE").length,time:trades.filter(x=>x.why==="TIME").length}}
function enter(a,i){return{at:i+1,price:a[i+1].o*(1+SLIP)}}
function manage(a,e,target,initialStop,maxHold,beTriggerNet=.5,earlyCheck=null){let stop=initialStop,armed=false;for(let j=e.at+1;j<=Math.min(a.length-1,e.at+maxHold);j++){const x=a[j];if(!armed&&net(e.price,x.h)>=beTriggerNet){armed=true;stop=Math.max(stop,priceForNet(e.price,.05))}if(x.l<=stop)return{at:j,pnl:net(e.price,Math.min(stop,x.o)*(1-SLIP)),why:armed?"BE":"STOP"};if(x.h>=target)return{at:j,pnl:net(e.price,target),why:"TARGET"};if(earlyCheck&&j===e.at+earlyCheck.minutes&&net(e.price,x.c)<earlyCheck.minNet)return{at:j,pnl:net(e.price,x.c*(1-SLIP)),why:"TIME"}}const j=Math.min(a.length-1,e.at+maxHold);return{at:j,pnl:net(e.price,a[j].c*(1-SLIP)),why:"TIME"}}
function simulateVwap(a,from,to){let busy=-1,signals=0;const trades=[];for(let i=Math.max(from,180);i<to-20;i++){if(i<=busy)continue;const vw=vwap(a.slice(i-59,i+1)),deviation=pct(vw,a[i].c),minDeviation=Math.max(2*COST_NET,1.5*atr(a,i,60));if(deviation>-minDeviation||a[i].c<=a[i].o||buyShare(a[i])<.5||buyShare(a[i])<=buyShare(a[i-1]))continue;signals++;const e=enter(a,i),potential=net(e.price,vw);if(potential<COST_NET)continue;const localLow=Math.min(...a.slice(i-9,i+1).map(x=>x.l))*.999,loss=net(e.price,localLow);if(loss< -1.0)continue;const stop=Math.min(localLow,priceForNet(e.price,-.15));const x=manage(a,e,vw,stop,15,.5,{minutes:10,minNet:0});trades.push(x);busy=x.at}return exitMetrics(trades,signals)}
function previousSession(a,i){const now=new Date(a[i].t),day=Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()),start=day-24*60*M+8*60*M,end=day-24*60*M+20*60*M;return a.filter(x=>x.t>=start&&x.t<end)}
function asianRows(a,i){const now=new Date(a[i].t),day=Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate());return a.filter(x=>x.t>=day&&x.t<=a[i].t)}
function simulateGap(a,from,to){let busy=-1,signals=0;const trades=[];for(let i=Math.max(from,1800);i<to-125;i++){if(i<=busy)continue;const d=new Date(a[i].t);if(d.getUTCHours()!==7||d.getUTCMinutes()!==0)continue;const prior=previousSession(a,i),asia=asianRows(a,i);if(prior.length<700||asia.length<400)continue;const fair=vwap(prior),deviation=pct(fair,a[i].c),threshold=1.5*atr(a,i,60),recentQ=avg(a.slice(i-29,i+1).map(x=>x.q)),priorQ=avg(prior.map(x=>x.q));if(deviation>=-threshold||recentQ>=priorQ)continue;signals++;const e=enter(a,i),potential=net(e.price,fair);if(potential<COST_NET)continue;const asiaLow=Math.min(...asia.map(x=>x.l))*.999,loss=net(e.price,asiaLow);if(loss< -1.5)continue;const stop=Math.min(asiaLow,priceForNet(e.price,-.2));const x=manage(a,e,fair,stop,120,.5,null);trades.push(x);busy=x.at}return exitMetrics(trades,signals)}
function synthetic(){const vwapCases=[{d:-1,min:.8,green:true,share:.55,prev:.45,ok:true},{d:-.5,min:.8,green:true,share:.55,prev:.45,ok:false}],gapCases=[{d:-1,thr:.7,thin:true,ok:true},{d:-.5,thr:.7,thin:true,ok:false}];return[...vwapCases.map(x=>({name:"cost_aware_vwap",pass:((x.d<=-x.min&&x.green&&x.share>=.5&&x.share>x.prev)===x.ok)})),...gapCases.map(x=>({name:"session_gap_fill",pass:((x.d<=-x.thr&&x.thin)===x.ok)}))]}
(async()=>{if(!Number.isFinite(END))throw Error("Invalid end");const start=END-DAYS*1440*M,a=await fetchSymbol("PUMPUSDT",start,END),cut=Math.floor(a.length/2),result={days:DAYS,minutes:a.length,periods:{early:[new Date(a[0].t).toISOString(),new Date(a[cut-1].t).toISOString()],control:[new Date(a[cut].t).toISOString(),new Date(a.at(-1).t).toISOString()]},costs:{feePerSide:FEE,entryAndExitSlippage:SLIP,roundTripFeeNet:COST_NET},synthetic:synthetic(),results:{cost_aware_vwap:{early:simulateVwap(a,0,cut),control:simulateVwap(a,cut,a.length)},session_gap_fill:{early:simulateGap(a,0,cut),control:simulateGap(a,cut,a.length)}}};console.log(JSON.stringify(result,null,2))})().catch(e=>{console.error(e.stack||e);process.exit(1)});
