#!/usr/bin/env node

/* Four fixed OHLCV hypotheses from external review. Research-only. */
const API="https://data-api.binance.vision/api/v3/klines",M=60000,DAYS=Number(process.argv[2]||180),END=Date.parse(process.argv[3]||"2025-12-31T07:55:00Z");
const FEE=.0021,SLIP=.0008,sum=x=>x.reduce((a,b)=>a+b,0),avg=x=>x.length?sum(x)/x.length:0,pct=(a,b)=>(b/a-1)*100;
const net=(e,x)=>((x*(1-FEE))/(e*(1+FEE))-1)*100;
async function fetchSymbol(symbol,start,end){const out=[];for(let c=start;c<end;){const r=await fetch(`${API}?symbol=${symbol}&interval=1m&startTime=${c}&endTime=${end-1}&limit=1000`);if(!r.ok)throw Error(`${symbol} HTTP ${r.status}`);const p=await r.json();if(!p.length)break;out.push(...p);c=+p[p.length-1][0]+M}return out.map(x=>({t:+x[0],o:+x[1],h:+x[2],l:+x[3],c:+x[4],q:+x[7],bq:+x[10]}))}
function align(s){const m=Object.fromEntries(Object.entries(s).map(([k,v])=>[k,new Map(v.map(x=>[x.t,x]))]));return[...m.P.keys()].filter(t=>m.B.has(t)&&m.S.has(t)).sort((a,b)=>a-b).map(t=>({t,P:m.P.get(t),B:m.B.get(t),S:m.S.get(t)}))}
function tr(a,i,k="P"){const x=a[i][k],p=a[i-1][k].c;return Math.max(x.h-x.l,Math.abs(x.h-p),Math.abs(x.l-p))}
function atr(a,i,n,k="P"){let s=0;for(let j=i-n+1;j<=i;j++)s+=tr(a,j,k);return s/n}
function sma(a,i,n,key="c",k="P"){return avg(a.slice(i-n+1,i+1).map(x=>x[k][key]))}
function std(a,i,n,center,k="P"){return Math.sqrt(avg(a.slice(i-n+1,i+1).map(x=>(x[k].c-center)**2)))}
function buyShare(x){return x.P.q?x.P.bq/x.P.q:.5}
function weightedVwapSigma(a,i,n){const rows=a.slice(i-n+1,i+1),q=sum(rows.map(x=>x.P.q)),v=q?sum(rows.map(x=>((x.P.h+x.P.l+x.P.c)/3)*x.P.q))/q:a[i].P.c,s=q?Math.sqrt(sum(rows.map(x=>x.P.q*(((x.P.h+x.P.l+x.P.c)/3-v)**2)))/q):0;return{v,s}}
const acceptZ=f=>f.z<=-2.5&&f.sigmaPct>=.55&&f.slope>=-.03&&f.green&&f.buyShare>=.55;
const acceptSqueeze=f=>f.squeezed&&f.closeAbove&&f.volumeRatio>=2.2;
const acceptLead=f=>f.leader&&f.pumpRet<=.1&&f.active;
const acceptSession=f=>f.rangePct<=.9&&f.closeAbove&&f.volumeRatio>=2.2;
function squeezeAt(a,i){const mid=sma(a,i,20),sd=std(a,i,20,mid),at=atr(a,i,20);return mid-2*sd>=mid-1.5*at&&mid+2*sd<=mid+1.5*at}
function fillStop(a,i,trigger,ttl){for(let j=i+1;j<=i+ttl;j++){const x=a[j].P;if(x.h>=trigger)return{at:j,price:Math.max(trigger,x.o)*(1+SLIP)}}return null}
function fillLimit(a,i,limit,ttl){for(let j=i+1;j<=i+ttl;j++){const x=a[j].P;if(x.l<=limit)return{at:j,price:Math.min(limit,x.o)}}return null}
function closeFixed(a,e,stop,target,maxHold,extraExit=null){for(let j=e.at+1;j<=Math.min(a.length-1,e.at+maxHold);j++){const x=a[j].P;if(x.l<=stop)return{at:j,pnl:net(e.price,Math.min(stop,x.o)*(1-SLIP)),why:"STOP"};if(x.h>=target)return{at:j,pnl:net(e.price,target),why:"TARGET"};if(extraExit&&extraExit(a,j))return{at:j,pnl:net(e.price,x.c*(1-SLIP)),why:"INVALIDATION"}}const j=Math.min(a.length-1,e.at+maxHold);return{at:j,pnl:net(e.price,a[j].P.c*(1-SLIP)),why:"TIME"}}
function metrics(t,signals,unfilled,rejected=0){const w=t.filter(x=>x.pnl>0),l=t.filter(x=>x.pnl<=0),gp=sum(w.map(x=>x.pnl)),gl=-sum(l.map(x=>x.pnl));let eq=0,peak=0,dd=0;for(const x of t){eq+=x.pnl;peak=Math.max(peak,eq);dd=Math.max(dd,peak-eq)}return{signals,filled:t.length,unfilled,rejected,wins:w.length,losses:l.length,winRate:t.length?w.length/t.length:null,averageNet:t.length?sum(t.map(x=>x.pnl))/t.length:null,totalNetPoints:sum(t.map(x=>x.pnl)),profitFactor:gl?gp/gl:null,maxSequentialDrawdownPoints:dd,targets:t.filter(x=>x.why==="TARGET").length,stops:t.filter(x=>x.why==="STOP").length,timeOrInvalidation:t.filter(x=>x.why!=="TARGET"&&x.why!=="STOP").length}}
function simulateZVwap(a,from,to){let busy=-1,signals=0,unfilled=0,rejected=0;const t=[];for(let i=Math.max(from,70);i<to-45;i++){if(i<=busy)continue;const now=weightedVwapSigma(a,i,60),old=weightedVwapSigma(a,i-5,60),f={z:now.s?(a[i].P.c-now.v)/now.s:0,sigmaPct:now.s/now.v*100,slope:pct(old.v,now.v)/5,green:a[i].P.c>a[i].P.o,buyShare:buyShare(a[i])};if(!acceptZ(f))continue;signals++;const e=fillLimit(a,i,a[i].P.c,2);if(!e){unfilled++;busy=i+2;continue}const target=now.v-.5*now.s;if(target<=e.price){rejected++;busy=e.at;continue}const stop=e.price*(1-.0085),x=closeFixed(a,e,stop,target,40);t.push(x);busy=x.at}return metrics(t,signals,unfilled,rejected)}
function simulateSqueeze(a,from,to){let busy=-1,signals=0,unfilled=0;const t=[];for(let i=Math.max(from,45);i<to-50;i++){if(i<=busy)continue;const squeezed=[0,1,2,3,4].every(d=>squeezeAt(a,i-d)),mid=sma(a,i,20),upper=mid+2*std(a,i,20,mid),volAvg=avg(a.slice(i-20,i).map(x=>x.P.q)),f={squeezed,closeAbove:a[i].P.c>upper,volumeRatio:a[i].P.q/Math.max(volAvg,1)};if(!acceptSqueeze(f))continue;signals++;const e=fillStop(a,i,a[i].P.h*1.0001,1);if(!e){unfilled++;busy=i+1;continue}const at=atr(a,i,20),stop=a[i].P.c-1.2*at,target=a[i].P.c+2.5*at,x=closeFixed(a,e,stop,target,45);t.push(x);busy=x.at}return metrics(t,signals,unfilled)}
function prefixes(a,k){const p=[0];for(const x of a)p.push(p.at(-1)+x[k].q);return p}
const rangeSum=(p,l,r)=>p[r+1]-p[l];
function dailyMedianVolumes(a,p,i){const end=i-1440,start=end-7*1440;if(start<0)return null;const ds=[];for(let d=0;d<7;d++)ds.push(rangeSum(p,start+d*1440,start+(d+1)*1440-1));ds.sort((x,y)=>x-y);return ds[3]}
function simulateLead(a,from,to){let busy=-1,signals=0,unfilled=0;const t=[],pP=prefixes(a,"P"),pB=prefixes(a,"B"),pS=prefixes(a,"S");for(let i=Math.max(from,8*1440);i<to-35;i++){if(i<=busy)continue;const bRet=pct(a[i-2].B.c,a[i].B.c),sRet=pct(a[i-2].S.c,a[i].S.c),pRet=pct(a[i-2].P.c,a[i].P.c),bVol=rangeSum(pB,i-1,i),sVol=rangeSum(pS,i-1,i),bBase=rangeSum(pB,i-21,i-2)/10,sBase=rangeSum(pS,i-21,i-2)/10,leader=(bRet>=.6&&bVol>=2*bBase)?"B":(sRet>=.8&&sVol>=2*sBase)?"S":null,med=dailyMedianVolumes(a,pP,i),v24=rangeSum(pP,i-1439,i),f={leader:leader!=null,pumpRet:pRet,active:med!=null&&v24>med};if(!acceptLead(f))continue;signals++;const e=fillStop(a,i,a[i].P.c*1.0002,1);if(!e){unfilled++;busy=i+1;continue}const stop=e.price*(1-.0075),target=e.price*(1+.017),extra=(rows,j)=>j>=e.at+2&&pct(rows[j-2][leader].c,rows[j-1][leader].c)<=-.2&&pct(rows[j-1][leader].c,rows[j][leader].c)<=-.2,x=closeFixed(a,e,stop,target,30,extra);t.push(x);busy=x.at}return metrics(t,signals,unfilled)}
function sessionSpec(t){const d=new Date(t),m=d.getUTCHours()*60+d.getUTCMinutes();if(m>=7*60+15&&m<=7*60+45)return{start:7*60};if(m>=13*60+45&&m<=14*60+15)return{start:13*60+30};return null}
function simulateSession(a,from,to){let busy=-1,signals=0,unfilled=0;const t=[];for(let i=Math.max(from,60);i<to-65;i++){if(i<=busy)continue;const spec=sessionSpec(a[i].t);if(!spec)continue;const d=new Date(a[i].t),day=Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()),startT=day+spec.start*M;let start=i;while(start>0&&a[start].t>=startT)start--;start++;const range=a.slice(start,start+15);if(range.length<15||range.at(-1).t!==startT+14*M)continue;const hi=Math.max(...range.map(x=>x.P.h)),lo=Math.min(...range.map(x=>x.P.l)),volAvg=avg(a.slice(i-20,i).map(x=>x.P.q)),f={rangePct:pct(lo,hi),closeAbove:a[i].P.c>hi,volumeRatio:a[i].P.q/Math.max(volAvg,1)};if(!acceptSession(f))continue;signals++;const e=fillStop(a,i,hi*1.0002,2);if(!e){unfilled++;busy=i+2;continue}const stop=(hi+lo)/2,target=e.price*1.018,x=closeFixed(a,e,stop,target,60);t.push(x);busy=x.at}return metrics(t,signals,unfilled)}
function synthetic(){const cases=[
 ["zscore_vwap",acceptZ,{z:-2.7,sigmaPct:.6,slope:-.01,green:true,buyShare:.58},true],["zscore_vwap",acceptZ,{z:-2,sigmaPct:.6,slope:-.01,green:true,buyShare:.58},false],
 ["volatility_squeeze",acceptSqueeze,{squeezed:true,closeAbove:true,volumeRatio:2.3},true],["volatility_squeeze",acceptSqueeze,{squeezed:true,closeAbove:true,volumeRatio:1.8},false],
 ["lead_lag",acceptLead,{leader:true,pumpRet:.05,active:true},true],["lead_lag",acceptLead,{leader:true,pumpRet:.2,active:true},false],
 ["session_open_squeeze",acceptSession,{rangePct:.7,closeAbove:true,volumeRatio:2.4},true],["session_open_squeeze",acceptSession,{rangePct:1.1,closeAbove:true,volumeRatio:2.4},false]
 ];return cases.map(([name,fn,f,expected])=>{const actual=fn(f);return{name,expected,actual,pass:actual===expected}})}
(async()=>{if(!Number.isFinite(END))throw Error("Invalid end");const start=END-DAYS*1440*M,[P,B,S]=await Promise.all([fetchSymbol("PUMPUSDT",start,END),fetchSymbol("BTCUSDT",start,END),fetchSymbol("SOLUSDT",start,END)]),a=align({P,B,S}),cut=Math.floor(a.length/2),run=(fn)=>({early:fn(a,0,cut),control:fn(a,cut,a.length)}),result={days:DAYS,minutes:a.length,periods:{early:[new Date(a[0].t).toISOString(),new Date(a[cut-1].t).toISOString()],control:[new Date(a[cut].t).toISOString(),new Date(a.at(-1).t).toISOString()]},costs:{feePerSide:FEE,marketSlippage:SLIP},synthetic:synthetic(),results:{zscore_vwap:run(simulateZVwap),volatility_squeeze:run(simulateSqueeze),lead_lag:run(simulateLead),session_open_squeeze:run(simulateSession)}};console.log(JSON.stringify(result,null,2))})().catch(e=>{console.error(e.stack||e);process.exit(1)});
